FROM arm32v7/python:3.10.5-slim-buster

ENV PYTHONUNBUFFERED 1

RUN \
    apt-get update -y \
    && apt-get install -y gcc gcc python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev g++ \
    # Clean up
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/

RUN addgroup --system fastapi \
    && adduser --system --ingroup fastapi fastapi

COPY --chown=fastapi:fastapi ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=fastapi:fastapi ./start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

COPY --chown=fastapi:fastapi . /app

WORKDIR /app

CMD ["/start"]
